#!/usr/bin/env bash

cd "$(dirname "$0")"

if [[ "$CI" = true ]]; then
  export VADER_OUTPUT_FILE='testresults.txt'
  vim -u <(cat minimalvimrc) +'Vader! indent/*.vader'
else
  vim -u <(cat minimalvimrc) +'Vader  indent/*.vader'
fi
